### ISSUE TITLE
NameError: name 'gradVertical' is not defined

### ISSUE THREAD

**Issue by ckkelvinchan** [sniklaus/softmax-splatting#1]
Hello, 

when I tried to use the softmax splatting, the following error occurred:

**NameError: name 'gradVertical' is not defined**

When I checked the code (line 330 of softsplat.py), it seems that _gradVertical_ and _gradHorizontal_ are not defined. Could you help me with that? Thank you very much!

**Comment by sniklaus** [comment]
Fixed in #49fe0708635ba3a5576a51dc1e8334e89c230be8, my apologies for the trouble. Please let me know in case you encounter any other issues, thanks!
