### ISSUE TITLE
problem with generating synthetic image

### ISSUE THREAD

**Issue by hogeman2** [sniklaus/softmax-splatting#11]
Nice work!

I have some problem reproducing your work. 
In my case, output image color is empathized. (some epoch G value is higher than original G value and some epoch R value is higher than original one)

Do you have any idea?

**Comment by sniklaus** [comment]
Thank you for the kind words! Would you mind elaborating on what you are referring to by "G" and "R"?

**Comment by hogeman2** [comment]
Thanks for your reply
Sorry for lack of my explanation G, R means color channel. 
I mean the colors from input image is changed after image synthetic module(Gridnet). green tree changes more green or less green or something.

**Comment by sniklaus** [comment]
I am afraid that I do not have enough information to help you debug this. This is also not an issue with softmax splatting per se, you can further see that no such issues were raised in #5.

**Comment by hogeman2** [comment]
Thanks I will close this issue.
