### ISSUE TITLE
Fig.1 in the paper

### ISSUE THREAD

**Issue by JihyongOh** [sniklaus/softmax-splatting#18]
Hello, 
thank you for your great work for VFI.
I have a question about Fig.1 in the paper.
How can I make a video figure like Fig.1 in the paper? (several independent videos(gif?) in one figure)
Can you provide information or tutorial about that?
Thank you,

Best regards,
Jihyong.

**Comment by sniklaus** [comment]
Thank you for the kind words! I used `\animategraphics` of the animate package: https://ctan.org/pkg/animate?lang=en

For inspiration, you can also see our 3D Ken Burns paper where we used many video figures: https://arxiv.org/abs/1909.05483

**Comment by JihyongOh** [comment]
Thank you for your kind reply!!
I have one more question about how the 12 videos (=2x6) attached in fig.1 are organized and imported by "animategraphics".
Specifically, if you used Latex, how did you simultaneously interlock the references ([39],[51],...) with 12 independent videos (gif?) separately? Was the Fig.1 created and imported into a single file containing 12 videos? If not, were12 independent videos imported with the animategraphics's option?

Best regards,
Jihyong.

**Comment by sniklaus** [comment]
It is six independent videos (one per method) as follows.

```
\begin{center}\centering
    \setlength{\tabcolsep}{0.06cm}
    \setlength{\itemwidth}{2.81cm}
    \hspace*{-\tabcolsep}\begin{tabular}{cccccc}
            \animategraphics[width=\itemwidth, poster=3, autoplay, palindrome, final, nomouse, method=widget]{12}{graphics/teaser/sepconv/}{00000}{00006}
        &
            \animategraphics[width=\itemwidth, poster=3, autoplay, palindrome, final, nomouse, method=widget]{12}{graphics/teaser/toflow/}{00000}{00006}
        &
            \animategraphics[width=\itemwidth, poster=3, autoplay, palindrome, final, nomouse, method=widget]{12}{graphics/teaser/cyclicgen/}{00000}{00006}
        &
            \animategraphics[width=\itemwidth, poster=3, autoplay, palindrome, final, nomouse, method=widget]{12}{graphics/teaser/ctxsyn/}{00000}{00006}
        &
            \animategraphics[width=\itemwidth, poster=3, autoplay, palindrome, final, nomouse, method=widget]{12}{graphics/teaser/dain/}{00000}{00006}
        &
            \animategraphics[width=\itemwidth, poster=3, autoplay, palindrome, final, nomouse, method=widget]{12}{graphics/teaser/ours/}{00000}{00006}
        \vspace{-0.1cm} \\
            \footnotesize SepConv - $\mathcal{L}_F$~\cite{Niklaus_ICCV_2017}
        &
            \footnotesize ToFlow~\cite{Xue_IJCV_2019}
        &
            \footnotesize CyclicGen~\cite{Liu_AAAI_2019}
        &
            \footnotesize CtxSyn - $\mathcal{L}_F$~\cite{Niklaus_CVPR_2018}
        &
            \footnotesize DAIN~\cite{Bao_CVPR_2019}
        &
            \footnotesize Ours - $\mathcal{L}_F$
        \\
    \end{tabular}\vspace{-0.2cm}
	\captionof{figure}{A difficult example for video frame interpolation. Our approach produces a high-quality result in spite of the delicate flamingo leg that is subject to large motion. \textit{This is a video figure that is best viewed using Adobe Reader.}}\vspace{-0.0cm}
	\label{fig:teaser}
\end{center}
```

The `graphics/teaser` folder structure is as follows (only "ctxsyn" is expanded for brevity).
![Screenshot_2020-10-18_19-25-08](https://user-images.githubusercontent.com/1238034/96394768-aa3f7d00-1177-11eb-8326-925ba1223c65.png)

A single frame, like `graphics/ctxsyn/0003.jpg`, looks as follows.
![00003](https://user-images.githubusercontent.com/1238034/96394831-d8bd5800-1177-11eb-9bc7-c877cbb78a5a.jpg)

**Comment by JihyongOh** [comment]
Wow, thank you for your very kind reply!!
It will help me a lot :) 👍
