### ISSUE TITLE
How to understand equation 3?

### ISSUE THREAD

**Issue by ProNoobLi** [sniklaus/softmax-splatting#19]
![image](https://user-images.githubusercontent.com/33815430/96393301-49ed2180-11f1-11eb-8703-9142f8dc733d.png)
As I understand, the q should be a pair of coordinate (x, y) in I0, then (q +  F[q]) should be the new location of I0 after farward warping based on flow map 0->t. However I don't understand why p minus the results above.

**Comment by sniklaus** [comment]
If `p` and `q + flow_at_q` cancel each other out, then the point `q` points to the point `p` with the respective optical flow vector. The "cancels each other out" warrants the minus.
