### ISSUE TITLE
Google Colab demo?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [sniklaus/softmax-splatting#21]
Hello.  
This work looks very impressive!  Would you consider sharing a [Google Colab notebook](https://colab.research.google.com/drive/1i5_uVHWOJlh2adRFT5BuDhoRftq9Oosx#scrollTo=lNc6HHfHDfnE) of your example code so that folks like myself with limited coding experience can try it out more easily.  Thank you!

**Comment by sniklaus** [comment]
A quick question before I start looking into this: what would you like the notebook to show/do?

**Comment by noobtoob4lyfe** [comment]
Thanks so much for the quick reply.  I'd like to be able to input a video or image sequence and get a 2x or 4x slow motion video as an output to compare the results to other frame interpolation methods.

**Comment by sniklaus** [comment]
My apologies, but we only provide the softmax splatting operator and not our video frame interpolation pipeline that utilizes softmax splatting. I am afraid that I am not allowed to release the implementation that you requested, sorry.

**Comment by noobtoob4lyfe** [comment]
Understood.  Thanks for looking into it.
