### ISSUE TITLE
about the holes in forward warping

### ISSUE THREAD

**Issue by gangsterless** [sniklaus/softmax-splatting#26]
very great work！
I noticed there exist holes in the forward warping result and sometimes holes are very big if the movement flow is large.
I also noticed  that "filling the holes" operator is very common in flow based intepolation method( including your previous work).
But  it seems you don't fill the holes before sending the warped frame into the synthetize net in  this work . I am just wondering how the synthetized net 'learn' about the missing holes in the warped frames. 
Apologize  for my poor English!
Looking forward to your reply. Thank you very much!

**Comment by sniklaus** [comment]
Good question! Splatting indeed leads to holes in the forward-warped results and there are multiple approaches of handling those. For example, "A Database and Evaluation Methodology for Optical Flow" forward warps flows, then fills the holes using an outside-in strategy, and then employs backwards warping. We wanted to keep our framework as simple as possible though, so we instead chose not to fill the holes at all. However, our synthesis network does not have to rely on inpainting though and it can most of the time just combine the information from the forward-warped first frame and the forward-warped second frame. Usually, the forward-warped first frame and the forward-warped second frame have their holes at different locations.

**Comment by kwea123** [comment]
Btw, holes exist for backward warping too, it is not specific to forward warping.
