### ISSUE TITLE
error

### ISSUE THREAD

**Issue by HadiAmirpour** [sniklaus/softmax-splatting#35]
Hi,

I face the following error when I run the code:

```
 input = input.contiguous(); assert(input.is_cuda == True)

TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by sniklaus** [comment]
Thanks for letting me know! I just fixed this in ce9b0c0793a92489bfd8a40480b70a37f51c85d2, please don't hesitate to reach out again in case this issue persists.

**Comment by HadiAmirpour** [comment]
Thanks Simon,

It has been solved. However, I have the other problem now:
: cannot connect to X server 

I can run sepconv in the same system without any problem

**Comment by sniklaus** [comment]
Looks like you are running this on a headless server. However, the following lines want to show images.

https://github.com/sniklaus/softmax-splatting/blob/ce9b0c0793a92489bfd8a40480b70a37f51c85d2/run.py#L60-L64

If you want to run this on a headless server you will have to modify these lines to save the images instead.

**Comment by HadiAmirpour** [comment]
Many thanks for your response. It works now. 

My last question: It seems the code works only for the images in the github not other images as flow.flo was provided for those images only. Am I right?

**Comment by sniklaus** [comment]
I am afraid that this repository only includes the code for the softmax splatting operator, not the full video frame interpolation pipeline. To try the softmax splatting on other images, you can, for example, use this: https://github.com/sniklaus/pytorch-pwc
