### ISSUE TITLE
About the size of the test image

### ISSUE THREAD

**Issue by sunnyCST** [sniklaus/softmax-splatting#41]
Thanks for your work. But when I tried the demo with my own images(which is 1920x1080), I met this problem:

Traceback (most recent call last):
  File "run_my.py", line 52, in <module>
    tenMetric = torch.nn.functional.l1_loss(input=tenOne, target=backwarp(tenInput=tenTwo, tenFlow=tenFlow), reduction='none').mean(1, True)
  File "/data/sunyn/miniconda3/envs/Softmax/lib/python3.6/site-packages/torch/nn/functional.py", line 2633, in l1_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/data/sunyn/miniconda3/envs/Softmax/lib/python3.6/site-packages/torch/functional.py", line 71, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)  # type: ignore
RuntimeError: The size of tensor a (1920) must match the size of tensor b (320) at non-singleton dimension 3

Does this demo support another size of the test images? Or it only supports the size of 320x320. Looking forward to your reply.

**Comment by sniklaus** [comment]
I am under the impression that you changed the input images but not the optical flow estimate. As such, the optical flow does not match the images. Please note that this repository only includes the softmax splatting operator.
