### ISSUE TITLE
Maximum splatting

### ISSUE THREAD

**Issue by 863689877** [sniklaus/softmax-splatting#42]
Thank you for your nice work!
As far as I know, there also has a forward warping method which using maximum operation.
How can I realize maximum splatting by modifying your code?

**Comment by sniklaus** [comment]
I am not aware of a fully differentiable way to do so, my apologies. If one does hard z-buffering, I am under the impression that it is still possible to get gradients for the input (what is being warped) and the flow, but not for the metric.
