### ISSUE TITLE
about bilinear kernel

### ISSUE THREAD

**Issue by 863689877** [sniklaus/softmax-splatting#44]
Thank you for your nice work!
The bilinear kernel in your paper is descriped as followed:
<a href="https://www.codecogs.com/eqnedit.php?latex=b(u)=max(0,1-|u_x|)\cdot&space;max(0,1-|u_y|)" target="_blank"><img src="https://latex.codecogs.com/gif.latex?b(u)=max(0,1-|u_x|)\cdot&space;max(0,1-|u_y|)" title="b(u)=max(0,1-|u_x|)\cdot max(0,1-|u_y|)" /></a>
As far as I know, bilinear operation is used on four regular two-dimensional points, and how to used it on the an irregular and arbitrary number of warped points? Please explain this problem, thanks.

**Comment by sniklaus** [comment]
I am afraid that I do not understand your question, my apologies. The bilinear kernel essentially means that we splat a pixel to four pixels, where the contribution to each of the four pixels is determined by the bilinear kernel.

https://github.com/sniklaus/softmax-splatting/blob/7ba7a19dc054674ae0407674372b6f0d8a36b2c7/softsplat.py#L32-L51

**Comment by 863689877** [comment]
![微信图片_20211021111240](https://user-images.githubusercontent.com/48486151/138205218-03518dd3-1345-43a8-b51c-1132782ffa6c.jpg)

**Comment by sniklaus** [comment]
That seems to match my implementation?
