### ISSUE TITLE
compile_with_cache deprecated

### ISSUE THREAD

**Issue by JHLew** [sniklaus/softmax-splatting#49]
Hi, thank you for sharing the code to the public.
I tried running your implementation, but seems like ```cupy.cuda.compile_with_cache()``` of cupy is deprecated.

I felt that this is too minor for a pull request,
so I am leaving this issue in case someone runs into the same problem.

The code seems to run properly once the function cupy_launch (lines 245-246 of ```softsplat.py```) is fixed as below.

```python
def cupy_launch(strFunction, strKernel):
    return cupy.RawModule(code=strKernel).get_function(strFunction)
```

Hope this helps anyone in need!

**Comment by sniklaus** [comment]
Thanks for sharing this! You were probably hitting this bug in CuPy: https://github.com/cupy/cupy/issues/6231

An alternative to changing the softmax splatting implementation would be to downgrade CuPy to an older version, or wait for the next version of CuPy.
