### ISSUE TITLE
Question about the paragraph containing Eq. 13

### ISSUE THREAD

**Issue by seb-le** [sniklaus/softmax-splatting#55]
First of all, thank you for your nice work.

I have a question about the paragraph (Softmax splatting. on page 4) containing Eq. 13 in the paper.

I think if we use depth as Z, the grass will appear instead of the car in Fig. 3 because distant objects (i.e., grass) are more important than the close object (i.e., car).

How can I understand this?

Thank you

**Comment by sniklaus** [comment]
Thank you for your interest in our paper! If you want to use depth, you can just provide -depth as the metric. However, depending on what you are working on you may want to use disparity instead (and disparity comes with the added bonus that you don't have to flip the sign).
