### ISSUE TITLE
where bilinear equation come from

### ISSUE THREAD

**Issue by hitbuyi** [sniklaus/softmax-splatting#57]
Hi, I am having a trouble in understanding bilinear interpolation in your paper

![bi](https://user-images.githubusercontent.com/10301777/193802671-e8ed8cb7-0d99-4634-b6a7-488210df6045.gif)

where is this equation come from? is there any materials(paper,book, tutorials as reference), thanks a lot

**Comment by sniklaus** [comment]
From the top of my head, I can only think of "Spatial Transformer Networks" which uses
![image](https://user-images.githubusercontent.com/1238034/198869111-931c58cc-1b15-49d5-900c-f4dae9133094.png)
as well. My apologies for not having a better reference.
