### ISSUE TITLE
Inquiry Regarding Licensing for Academic Use

### ISSUE THREAD

**Issue by YukiKondo11** [sniklaus/softmax-splatting#62]
We are considering utilizing your remarkable work for academic purposes. However, regarding the license, we aim to respect your licensing preferences to the fullest while still wishing to use it. Therefore, we would appreciate it if you could address the following questions:

While the license of this code explicitly mentions academic use, we couldn't find further details on whether it requires inheriting the license or other specifics.
Would it be possible to consider replacing this code's license with standardized licenses such as AFL, Academic Public License, etc.?
Alternatively, would referencing the target code, as demonstrated [here](https://github.com/feinanshan/M2M_VFI/blob/main/Train/vfi/model/softsplat.py), suffice?

We appreciate your assistance in clarifying these matters.

**Comment by sniklaus** [comment]
Thank you for the kind words and for being careful about licensing! You can just do what is done in the M2M repo and leave a note where the code came from. Within the next month or two, I will also provide a pip-installable package for softmax splatting. At that point you don't even have to copy the code anymore. :+1:

**Comment by YukiKondo11** [comment]
Thank you for your reply, and I'm very looking forward to the pip install version!
